import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: './fonts/Inter_24pt-Regular.ttf',
  variable: '--font-inter',
  display: 'swap',
  preload: true,
  fallback: ['system-ui', 'arial'], // Add fallback fonts
});

const greatVibes = localFont({
  src: './fonts/GreatVibes-Regular.ttf',
  weight: "400",
  variable: '--font-great-vibes',
  display: 'swap',
  preload: true,
  fallback: ['cursive'], // Add fallback fonts
});

export const metadata: Metadata = {
  title: "Creative Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${greatVibes.variable}`}>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}

